# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['1.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'tkinter',
        'tkinter.ttk',
        'PIL',
        'PIL._tkinter_finder',
        'cv2',
        'numpy',
        'pandas',
        'matplotlib',
        'matplotlib.backends.backend_tkagg',
        'telebot',
        'yaml',
        'sqlite3',
        'json',
        'threading',
        'datetime',
        'time',
        'pathlib',
        'collections',
        'math',
        'warnings',
        'scipy',
        'scipy.interpolate',
        'scipy.stats',
        'openpyxl',
        'ultralytics',
        'ultralytics.nn.tasks',
        'ultralytics.models.yolo.detect.train',
        'ultralytics.models.yolo.detect.predict',
        'ultralytics.models.yolo.detect.val',
        'ultralytics.utils.torch_utils',
        'ultralytics.utils.checks',
        'ultralytics.utils.downloads',
        'ultralytics.utils.ops',
        'ultralytics.utils.metrics',
        'ultralytics.utils.loss',
        'ultralytics.utils.plotting',
        'ultralytics.data.augment',
        'ultralytics.data.utils',
        'ultralytics.data.dataset',
        'torch',
        'torchvision',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='CrayfishAIStudio',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # False - без консоли, True - с консолью для отладки
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None  # можно добавить иконку: icon='icon.ico'
)